//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JerryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPackageTask
    {
        public int Id { get; set; }
        public int CustomerID { get; set; }
        public int PackageID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual CustomerPackage CustomerPackage { get; set; }
    }
}
